# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e4758739229817a13ee11b9948757240a7aaef0a3552d608bb3cfbc3243d7f4740db94798f462f15cec1181c0c9a2a13ce39ee22d29f8b3c2f18c3148e17275

test:
  secret_key_base: 0f1c5634b44221604beec42e0fb777c1d6a84db2825acdabc10caad884ab4b58b871b969d0a4e00daff5a1a5969cafa7a0b801ab702b31ee1f35475b208eaef6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
